### PR TITLE
(Notification.dart): Fix push notifications not working in background on Android when app is terminated

### LINKED ISSUE #42: [Android] No push notifications while app is killed
Hello!

I have problem with push notifications on Android while app is killed.
I do have Firebase push notifications in my app which are working fine. While sending push from Firebase console I am receiving it no matter if the app is in foreground, background or killed.
Push notification from talkJs are showing only while the app is in foreground or background.
No chat notifications are received while app is killed. This behavior appy only to Android (iOS is seems to be working).

Looking for help or confirmation that pushes from talkJs chat are working on Android while the app is terminated.
Thank you!

### PR DESCRIPTION
**Pull request by vickz84259**
Fixes #42

This bug occured because the code previously assumed that the main isolate would always be available even when the app has been terminated. When the app has been terminated and a notification arrives, the handler is ran inside a background isolate. No main isolate is started.

Hence the fix is to handle all the processing inside the background isolate.

While testing, it was noted that `_androidSettings` would be blank in the above case. To fix this we encode the data and store in shared preferences.

### CODE REVIEW

File: lib/src/notification.dart [hunk 1]
```diff
@@ -86,13 +85,61 @@ class AndroidSettings {
     this.vibrate,
     this.vibrationPattern,
   });
+
+  AndroidSettings.fromString(Map<String, dynamic> json)
```
Comment (bugnano) [inline lib/src/notification.dart:89]: Minor nitpick: Shouldn't it be called `fromJson` instead?

File: lib/src/notification.dart [hunk 2]
```diff
@@ -102,7 +149,6 @@ AndroidSettings? _androidSettings;
 final _activeNotifications = <String, List<String>>{};
 int _nextId = 0;
 final _showIdFromNotificationId = <String, int>{};
-final _receivePort = ReceivePort();
```
Comment (bugnano) [inline lib/src/notification.dart:105]: By removing the port, if/when we want to implement handlers for clicking on a notification, how do we communicate with the main app?

File: lib/src/notification.dart [hunk 3]
```diff
@@ -349,6 +391,10 @@ Future<void> registerAndroidPushNotificationHandlers(
 
   _androidSettings = androidSettings;
 
+  // Save push notification settings to shared preferences.
+  final preferences = await SharedPreferences.getInstance();
+  preferences.setString(ANDROID_SETTINGS, jsonEncode(_androidSettings));
+
```
Comment (bugnano) [inline lib/src/notification.dart:397]: Is there a possibility that 2 notifications arrive before they are handled, so that the `ANDROID_SETTINGS` string is overwritten, thus handling only the second notification?
If so, it would be better to have a list, and append to that, right?

**Review by bugnano — COMMENTED** [review]
I have a minor nitpick and 2 questions.

File: lib/src/notification.dart (hunk 3 above)
Comment (vickz84259) [reply lib/src/notification.dart:397]: No, it's not possible. `registerAndroidPushNotificationHandlers` is only called on startup inside the `main` function. When the app has been terminated and a notification arrives, Dart just starts a service called `FlutterFirebaseMessagingBackgroundService` if it is not already running. This service then only calls the handler we passed to `FirebaseMessaging.onBackgroundMessage` below.

File: lib/src/notification.dart (hunk 1 above)
Comment (vickz84259) [reply lib/src/notification.dart:89]: How about `fromJsonString`?

File: lib/src/notification.dart (hunk 2 above)
Comment (vickz84259) [reply lib/src/notification.dart:105]: I've had a look at `flutter_local_notifications` and I see that the `onDidReceiveNotificationResponse` handler is called in the main isolate. Also there is the `getNotificationAppLaunchDetails` method that can be used to get info when a notification results in an app being launched. 

So I don't see us needing to use the port again.

**Review by bugnano — APPROVED** [review]
LGTM👍
